# .github/workflows/push-dist.yml

name: Push dist

on:
  push:
    branches:
      - main
      - master

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - name: "Install StepSecurity Action"
        id: step_security
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm install 
      - uses: kategengler/put-built-npm-package-contents-on-branch@844ca5b101a21b83924e746aa74c5c9f6f2c0e46 # v1.0.0
        with:
          working-directory: addon
          branch: ${{ github.head_ref || github.ref_name }}-dist
          token: ${{ secrets.GITHUB_TOKEN }}
